"""carford models

Revision ID: 9de713bbda55
Revises: 
Create Date: 2022-10-23 10:51:33.400168

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9de713bbda55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
                    sa.Column('id', sa.String(length=200), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('email', sa.String(length=80), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('admin',
                    sa.Column('id', sa.String(length=200), nullable=False),
                    sa.Column('person_id', sa.String(
                        length=200), nullable=True),
                    sa.Column('password', sa.String(
                        length=100), nullable=False),
                    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle',
                    sa.Column('id', sa.String(length=200), nullable=False),
                    sa.Column('person_id', sa.String(
                        length=200), nullable=True),
                    sa.Column('model', sa.String(length=20), nullable=False),
                    sa.Column('color', sa.String(length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('admin')
    op.drop_table('person')
    # ### end Alembic commands ###
